[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]

[book]
authors = ["Typewritergoblin"]
language = "en"
multilingual = false
src = "src"
title = "Icara 5ish Setting"

[output.html.fold]
enable = true
level = 1