[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[book]
authors = ["Typewritergoblin"]
language = "en"
multilingual = false
src = "src"
title = "Icara 5ish Setting"

[output.html.fold]
enable = true
level = 1